version: '3.7'
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
    container_name: odoo-web
    healthcheck:
      test: curl -fs http://localhost:8069/web/database/selector || exit 1
      start_period: 40s
      interval: 15s
      timeout: 5s
      retries: 3
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
      - ./addons_requirements.txt:/addons_requirements.txt

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo # odoo預設，config沒額外設定 entrypoint.sh 會帶入這組
      - POSTGRES_PASSWORD=odoo

      - PGDATA=/var/lib/postgresql/data/pgdata
    container_name: odoo-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=odoo --dbname=odoo_db"] #dbname設為你第一次建立db的名稱
      start_period: 20s
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

  hapi:
    image: "hapiproject/hapi:latest" # 容器疑似沒有裝bash，healthcheck無法使用
    container_name: hapi-fhir
    # healthcheck:
    #   test: curl -fs http://localhost:8080/fhir || exit 1
    #   start_period: 40s
    #   interval: 15s
    #   timeout: 10s
    #   retries: 2
    ports:
      - "8080:8080"
    volumes:
      - hapi-data:/data/hapi
    configs:
      - source: hapi
        target: /app/config/application.yaml

configs:
  hapi:
    file: ./config/hapi.application.yaml


volumes:
  odoo-web-data:
  odoo-db-data:
  hapi-data: