version: '3.7'
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
    healthcheck:
      test: curl -fs http://localhost:8069/web/database/selector || exit 1
      interval: 1m
      timeout: 5s
      retries: 2
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
      - ./addons_requirements.txt:/addons_requirements.txt

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo # odoo預設，config沒額外設定 entrypoint.sh 會帶入這組
      - POSTGRES_PASSWORD=odoo

      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=odoo --dbname=odoo_db"] #dbname設為你第一次建立db的名稱
      interval: 1m30s
      timeout: 5s
      retries: 2
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

  hapi:
    image: "hapiproject/hapi:latest"
    healthcheck:
      test: curl -fs http://localhost:8080/hapi/fhir/metadata || exit 1
      interval: 1m30s
      timeout: 5s
      retries: 2
    depends_on:
      - db_fhir
    ports:
      - "8080:8080"
    volumes:
      - hapi-web-data:/data/hapi
    configs:
      - source: hapi
        target: /app/config/application.yaml

  db_fhir:
    image: postgres:15
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=hapi
      - POSTGRES_PASSWORD=hapi
      - POSTGRES_PORT=5433
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=hapi --dbname=hapi"]
      interval: 1m
      timeout: 5s
      retries: 2

    volumes:
      - fhir-db-data:/var/lib/postgresql/data/pgdata

configs:
  hapi:
    file: ./config/hapi.application.yaml



volumes:
  odoo-web-data:
  odoo-db-data:
  hapi-web-data:
  fhir-db-data: