version: '3.5'
services:
  web:
    # image: odoo:16.0
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
    env_file:
      - .env
    healthcheck:
      test: curl -fs http://localhost:8069/web/database/selector || exit 1
      interval: 1m
      timeout: 5s
      retries: 2
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./addons_requirements.txt:/addons_requirements.txt
      # - ./odoo-log-data:/var/log/odoo
    # command: 
    #   sh -c "pip install -r /addons_requirements.txt && odoo"
    # command: 
    #   odoo
    # command:
      # odoo --db_user odoo16 --db_password odoo16 --init addons --database odoo
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=${POSTGRES_USER}"]
      interval: 1m30s
      timeout: 5s
      retries: 2
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-web-data:
  odoo-db-data: