spring:
  datasource:
    url: 'jdbc:postgresql://db:5432/hapi'
    username: odoo
    password: odoo
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
      hibernate.search.enabled: false
      fhir_version: R5
