name: Odoo extra-addons CI
run-name: Build and Test extra-addons by ${{ github.actor }}
on:
  push:
    branches:
      - "dev-**"
  pull_request:
    branches:
      - "master"

jobs:
  Build_and_Test_addons:
    runs-on: ubuntu-latest  # 使用Ubuntu Runner虛擬環境

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 檢出代碼到工作目錄

    - name: docker compose build
      run: |
        docker-compose build

    - name: docker compose up
      run: |
        docker-compose up -d

    - name: Wait for health checks
      run: |
        timeout 60s sh -c 'until docker ps | grep odoo-db | grep -q healthy; do echo "Waiting for odoo_db to be healthy..."; sleep 2; done'
        timeout 240s sh -c 'until docker ps | grep odoo-web | grep -q healthy; do echo "Waiting for odoo_web to be healthy..."; sleep 2; done'

    # - name: manually wait for hapi-fhir
    #   run: |
    #     count=0
    #     while : ; do
    #       count=$((count+1))
    #       curl -v -s -o /dev/null -w "%{http_code}" -X GET 'http://localhost:8080/fhir/$meta'
    #       response=$(curl -s -o /dev/null -w "%{http_code}" -X GET 'http://localhost:8080/fhir/$meta')
      
    #       if [[ $response -eq 200 ]]; then
    #           echo "HAPI-FHIR API is ready!"
    #           break
    #       elif [[ $count -gt 30 ]]; then
    #           echo "reached maximum attempts, exiting"
    #           exit 1
    #       else
    #           echo "HAPI-FHIR API is not ready yet, $count of 30 attempts, will try again in 2s..."
    #           sleep 2
    #       fi
    #     done
    
    # hapi-fhir會有連線錯誤，暫時忽略測試：
    # 出現"Recv failure: Connection reset by peer"錯誤，這個問題一般來說是因為在curl嘗試建立連線之後，對方伺服器強制關閉了這個連線。
    # *   Trying 127.0.0.1:8080...
    # * Connected to localhost (127.0.0.1) port 8080 (#0)
    # > GET /fhir/$meta HTTP/1.1
    # > Host: localhost:8080
    # > User-Agent: curl/7.81.0
    # > Accept: */*
    # > 
    # * Recv failure: Connection reset by peer
    # * Closing connection 0
    
        
    - name: Stop Docker Compose
      run: docker-compose down


  # Package_to_DockerHub:
  #   needs: Test_addons
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4  # 檢出代碼到工作目錄

  #   - name: Login to Docker Hub
  #     uses: docker/login-action@v2
  #     with:
  #       username: ${{ secrets.DOCKERHUB_USERNAME }}
  #       password: ${{ secrets.DOCKERHUB_TOKEN }}

  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v2
      
  #   - name: Build and push
  #     uses: docker/build-push-action@v4
  #     with:
  #       context: https://github.com/hank1224/odoo_landseed_HIS/tree/docker-compose_env
  #       file: ./Dockerfile
  #       push: true
  #       tags: ${{ secrets.DOCKERHUB_USERNAME }}/odoo_landseed_his:latest

  # Depolyment:
  #   needs: [Test_addons, Package_to_DockerHub]
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4

  #   - name: Set up Azure CLI
  #     uses: azure/login@v1
  #     with:
  #       creds: ${{ secrets.AZURE_CREDENTIALS }}