name: Odoo addons Automate CI
run-name: ${{ github.actor }} is testing addons build
on: 
  push:
    branches:
      - "hank1224-setting-actions.yml"
  pull_request:
    branches: ["master"]

jobs:
  build_env:
    runs-on: ubuntu-latest  # 使用Ubuntu Runner虛擬環境

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 檢出代碼到工作目錄

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Set up dependencies
      run: |
        sudo apt install python3-pip libldap2-dev libpq-dev libsasl2-dev

    - name: pip requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r extra-addons-requirements.txt
    
    - name: Set up PostgreSQL 15
      run: |
        cd psql_docker
        docker-compose up -d
        cd ..

    - name: Set up Odoo 16
      run: |
        python wait-for-psql.py --timeout=30
        python odoo-bin -c conf/odoo.conf --stop-after-init

    - name: Get extra-addon names
      run: |
        folders=$(ls -d extra-addons/* | sort -t / -k 2)
        echo $folders

    - name: Init and Test extra-addons
      run: |
        python odoo-bin -c conf/odoo.conf --test-enable --stop-after-init --init=$folders