name: Odoo addons Automate CI
run-name: ${{ github.actor }} is testing addons build
on: 
  push:
    branches:
      - "hank1224-setting-actions.yml"
  pull_request:
    branches: ["master"]

jobs:
  build_env:
    runs-on: ubuntu-latest  # 使用Ubuntu Runner虛擬環境

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 檢出代碼到工作目錄

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
          
    - name: setup.py
      run: |
        python setup.py install

    - name: Set up Ubuntu dependencies
      run: |
        apt-get update && \
        apt-get install -y --no-install-recommends \
            ca-certificates \
            curl \
            dirmngr \
            fonts-noto-cjk \
            gnupg \
            libssl-dev \
            node-less \
            npm \
            python3-magic \
            python3-num2words \
            python3-odf \
            python3-pdfminer \
            python3-pip \
            python3-phonenumbers \
            python3-pyldap \
            python3-qrcode \
            python3-renderpm \
            python3-setuptools \
            python3-slugify \
            python3-vobject \
            python3-watchdog \
            python3-xlrd \
            python3-xlwt \
            xz-utils \
        && curl -o wkhtmltox.deb -sSL https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.buster_amd64.deb \
        && echo 'ea8277df4297afc507c61122f3c349af142f31e5 wkhtmltox.deb' | sha1sum -c - \
        && apt-get install -y --no-install-recommends ./wkhtmltox.deb \
        && rm -rf /var/lib/apt/lists/* wkhtmltox.deb

    - name: pip extra-addons-requirements
      run: |
        # python -m pip install --upgrade pip
        # pip install -r requirements.txt
        pip install -r extra-addons-requirements.txt
    
    - name: Set up PostgreSQL 15
      run: |
        cd psql_docker
        docker-compose up -d
        cd ..

    - name: Set up Odoo 16
      run: |
        wait-for-psql.py --timeout=30 
        python odoo-bin -c conf/odoo.conf --stop-after-init

    - name: Get extra-addon names
      run: |
        directories=$(ls -d /extra-addons/*/)
        folder_names=""
        for dir in $directories
        do
            folder_name=$(basename $dir)
            folder_names+=",$folder_name"
        done
        folder_names=${folder_names:1}
        echo "extra-addons folder names: $folder_names"

    - name: Init and Test extra-addons
      run: |
        python odoo-bin -c conf/odoo.conf --test-enable --stop-after-init --init=$folder_names