name: Odoo extra-addons CICD
run-name: Build and Deploy extra-addons by ${{ github.actor }}
on: 
  pull_request:
    branches:
      - "main"

jobs:
  Build_and_Test_addons:
    runs-on: ubuntu-latest  # 使用Ubuntu Runner虛擬環境

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 檢出代碼到工作目錄

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Set up pip Dependencies
      run: |
        sudo apt install python3-pip libldap2-dev libpq-dev libsasl2-dev

    - name: Install pip requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r extra-addons-requirements.txt
    
    - name: Set up PostgreSQL 15
      run: |
        cd psql_docker
        docker-compose up -d
        cd ..

    - name: Init Odoo 16
      run: |
        python wait-for-psql.py --timeout=30
        python odoo-bin -c conf/odoo.conf --stop-after-init

    - name: Get extra-addon names
      run: |
        directories=$(ls -d extra-addons/*/)
        folder_names=""
        for dir in $directories
        do
            folder_name=$(basename $dir)
            folder_names+=",$folder_name"
        done
        folder_names=${folder_names:1}
        echo "FOLDER_NAMES=$folder_names" >> $GITHUB_ENV

    - name: Init and Test extra-addons
      run: |
        echo $FOLDER_NAMES
        python odoo-bin -c conf/odoo.conf --stop-after-init --init=$FOLDER_NAMES

  # Package_to_DockerHub:
  #   needs: Test_addons
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4  # 檢出代碼到工作目錄

  #   - name: Login to Docker Hub
  #     uses: docker/login-action@v2
  #     with:
  #       username: ${{ secrets.DOCKERHUB_USERNAME }}
  #       password: ${{ secrets.DOCKERHUB_TOKEN }}

  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v2
      
  #   - name: Build and push
  #     uses: docker/build-push-action@v4
  #     with:
  #       context: https://github.com/hank1224/odoo_landseed_HIS/tree/docker-compose_env
  #       file: ./Dockerfile
  #       push: true
  #       tags: ${{ secrets.DOCKERHUB_USERNAME }}/odoo_landseed_his:latest

  # Depolyment:
  #   needs: [Test_addons, Package_to_DockerHub]
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4

  #   - name: Set up Azure CLI
  #     uses: azure/login@v1
  #     with:
  #       creds: ${{ secrets.AZURE_CREDENTIALS }}