# This file will be move to root directory in addons_CICD.yml
version: '3.5'
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
    healthcheck:
      test: curl -fs http://localhost:8069/web/database/selector || exit 1
      interval: 1m
      timeout: 5s
      retries: 2
    volumes:
      - odoo-web-data:/var/lib/odoo
      - conf/odoo.conf:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
      - extra-addons_requirements.txt:/addons_requirements.txt

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=odoo --dbname=odoo"] #dbname設為你第一次建立db的名稱
      interval: 1m30s
      timeout: 5s
      retries: 3
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-web-data:
  odoo-db-data: